### ISSUE TITLE
Launch Apps Missing

### ISSUE THREAD

**Issue by mkallmanga** [K1DBO/slice-master-6000#10]
I have installed Slice Master v10.5e on a Flex 6400 and on the [Launch][A] and [B] tabs I only see DM780. I do not see WSJT-X and FLDigi. I do have them installed.  I tried deleting the config.ini and that made no difference.

Mark
N4MKA

[config.zip](https://github.com/K1DBO/slice-master-6000/files/2578874/config.zip)

**Comment by K1DBO** [comment]
Hi Mark,

My apologies for the slow response.  My email from github has been landing in my spam folder.  I'm generally more responsive if you send to the support address in the Slice Master splash screen.... or I could figure out how to get these messages to show up somewhere else!

It sounds like you have installed your WSJT-X and fldigi executable in a non-standard location.  You can edit Slice Master's config.ini to tell it where the executables are on your computer and it should get you going.

--Don

**Comment by mkallmanga** [comment]
That did the trick.

Thanks

Mark Allman
N4MKA
