### ISSUE TITLE
spots with cwskimmer and slicemaster not working on some bands

### ISSUE THREAD

**Issue by ve3wej** [K1DBO/slice-master-6000#16]
we have tried several times to have spots on our 6300, but it will only work on 40 and 80, is there some reason I can not get it to show on 30, 20 , and higher??

**Comment by ve3wej** [comment]
confirmed that slicemaster v0.10.7c works on 40 , 60, and 80 only, spotting what cwskimmer hears. this is with smartsdr v3.2.31, but soon to be upgraded. are there still some api programming to fix??  or is it just me and another local having this issue

**Comment by ve3wej** [comment]
still have recveived no answer or help on this issue

**Comment by K1DBO** [comment]
This issue is now fixed as of v0.10.8a.

**Comment by ve3wej** [comment]
Did not help

sent via LG hand held device
