### ISSUE TITLE
UI 

### ISSUE THREAD

**Issue by jshowelljr** [K1DBO/slice-master-6000#2]
Not displaying form correctly in 1920 x 1080 environment. (Win 10) New issue introduced in 0.9.18

![slicemasterformdisplayissue](https://user-images.githubusercontent.com/36698533/36485869-2ecc2008-16eb-11e8-8902-ce47d40fb847.PNG)

**Comment by K1DBO** [comment]
Thanks for opening the issue.

The problem you are seeing is related to some expectations about your HRD installation.  The expectations have been adjusted and v0.9.18c is now available and more likely to work for you.

**Comment by jshowelljr** [comment]
v09.18c fixes it.  Thanks!
