### ISSUE TITLE
slice master terminates CW skimmer

### ISSUE THREAD

**Issue by k8ki** [K1DBO/slice-master-6000#20]
I try to run cw skimmer using slice master, but as soon as slice master starts I get message: slice_master.tick err=TypeError("cannot concatenate 'str' and 'NoneType' objects",). Then: cwskimmer.disable_launch Disabling CW Skimmer slice='A', and cwskimmer.terminate Closing CW Skimmer process. slice='A'.
I use a Flex 6500 radio. Software v3.4.21. Slice Master is v.0.10.8a. Slice Master runs after Flex software running and stable.
DAX working ok. Smart Link working, but this radio is local via CAT6 cable.

I don't understand the problem, nor what these messages are telling me.
Thanks de bob k8ki

**Comment by K1DBO** [comment]
I'm happy to help, but I dont usually use this issue tracker for support. Please scroll to the bottom of the README for support instructions.

Thanks.
--Don
