### ISSUE TITLE
No WSJT-X Spots

### ISSUE THREAD

**Issue by imagesafari** [K1DBO/slice-master-6000#22]
I'm launching WSJT-X and it all works, but I'm not getting any spots, either on the panadapter or via the telnet aggregation server.

WSJT-X is configured to report via multicast, to support JT Alert & GridTracker, etc.

Where is SliceMaster looking to get its spots from WSJT-X? Could enabling multicast be breaking that?

Thanks & 73

**Comment by K1DBO** [comment]
Slice Master looks to the ALL.txt file for spot information.  The network settings shouldnt matter.  Send an email to the address you see when Slice Master starts up.  Please check the end of the README for instructions on including your log files in the email.

**Comment by imagesafari** [comment]
Looks like that was it. I'm not sure if this is a WSJT-X Improved-only feature or if it is in the mainline WSJT-X now too, but on the latest release candidate, I've got this option selected - so it is writing to a file named 2023-ALL.txt not ALL.txt - I tried changing the setting, and spots appeared.

![172-238-max](https://github.com/K1DBO/slice-master-6000/assets/395969/8b7bcfe0-3092-4f81-8fc5-fe6a42502550)

**Comment by K1DBO** [comment]
Ok, that makes sense.  In earlier releases (I think) it used to be on by default.

**Comment by imagesafari** [comment]
Maybe a feature request to specify the name of the ALL.txt file to watch
for spots?

**Comment by K1DBO** [comment]
I think the best option here is to have Slice Master determine which file WSJTx is writing to and to read from that one.
