### ISSUE TITLE
BitDefender quarantines 0.10.4c

### ISSUE THREAD

**Issue by jshowelljr** [K1DBO/slice-master-6000#4]
Don - FYI... slice-master-6000-v0.10.4c.zip gets quarantined by BitDefender (my virus checker). Previous versions work fine.  
![qrarantine](https://user-images.githubusercontent.com/36698533/42046019-ef7bac7c-7aca-11e8-8e9b-68f7db80df24.JPG)

John, AF3K

**Comment by K1DBO** [comment]
Hi John,

Trying to keep all virus scanners happy is like hitting a moving target.  Bitdefender is fine with v0.10.5b, for example, but sophos and crowdstrike are a little cranky about it.  You cant win them all.

--Don
